// Victor Jesus Maximo Abundio
// Ing. Sistemas Computacionales
// Tec Campus Vallarta
// 28/Octubre/2020

package cajerosimuladorexamen;
import clases.Banco;
import java.awt.Component;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author victo
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        
        this.setLocationRelativeTo(null);        
        cajero.fncInicializarCuentas();
        fncInsertarPicture(this.panelBackground, "/img/background.jpg", false);
        for(int item = 0; item < this.cajero.cuentas.length; item++){
            this.listaCuentas.addItem(cajero.cuentas[item].getStrNombre());
        }
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        listaCuentas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnIngresarSaldo = new javax.swing.JButton();
        btnConsultarSaldo = new javax.swing.JButton();
        btnRetirarSaldo = new javax.swing.JButton();
        panelFoto = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de cajero ");
        setResizable(false);

        listaCuentas.setForeground(new java.awt.Color(255, 255, 255));
        listaCuentas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaCuentasItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Seleccione una cuenta: ");

        btnIngresarSaldo.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarSaldo.setText("Ingresar saldo");
        btnIngresarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIngresarSaldoMouseReleased(evt);
            }
        });

        btnConsultarSaldo.setBackground(new java.awt.Color(153, 153, 153));
        btnConsultarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarSaldo.setText("Consultar saldo");
        btnConsultarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConsultarSaldoMouseReleased(evt);
            }
        });

        btnRetirarSaldo.setBackground(new java.awt.Color(102, 153, 0));
        btnRetirarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirarSaldo.setText("Retirar saldo");
        btnRetirarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRetirarSaldoMouseReleased(evt);
            }
        });

        panelFoto.setBackground(new java.awt.Color(255, 255, 255));
        panelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnIngresarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(btnRetirarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarSaldo)
                    .addComponent(btnConsultarSaldo)
                    .addComponent(btnRetirarSaldo))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarSaldoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarSaldoMouseReleased
        // TODO add your handling code here:
        int cliente = this.listaCuentas.getSelectedIndex();
        this.cajero.fncRetirar(cajero.cuentas[cliente] );
    }//GEN-LAST:event_btnRetirarSaldoMouseReleased

    private void listaCuentasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaCuentasItemStateChanged
        // TODO add your handling code here:
        int cliente = this.listaCuentas.getSelectedIndex();
        this.fncInsertarPicture(panelFoto, this.cajero.cuentas[cliente].getStrPicture(), true);
        
    }//GEN-LAST:event_listaCuentasItemStateChanged

    private void btnConsultarSaldoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSaldoMouseReleased
        // TODO add your handling code here:
        int cliente = this.listaCuentas.getSelectedIndex();
        this.cajero.fncConsulta(cajero.cuentas[cliente] );
    }//GEN-LAST:event_btnConsultarSaldoMouseReleased

    private void btnIngresarSaldoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarSaldoMouseReleased
        // TODO add your handling code here:
        int cliente = this.listaCuentas.getSelectedIndex();
        this.cajero.fncIngresar(cajero.cuentas[cliente] );
    }//GEN-LAST:event_btnIngresarSaldoMouseReleased
    
    private void fncInsertarPicture(JPanel contenedor, String url, boolean vaciar){
        
        if(vaciar) contenedor.removeAll();
        
        ImageIcon icono = new ImageIcon( getClass().getResource(url) );
        JLabel etiquetaImagen = new JLabel();
        etiquetaImagen.setBounds(0, 0, contenedor.getWidth(), contenedor.getHeight());
        etiquetaImagen.setIcon( new ImageIcon(icono.getImage().getScaledInstance(etiquetaImagen.getWidth(), etiquetaImagen.getHeight(), Image.SCALE_SMOOTH)) );
        contenedor.add(etiquetaImagen);
        
        if(vaciar) contenedor.validate();
        if(vaciar) contenedor.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnIngresarSaldo;
    private javax.swing.JButton btnRetirarSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> listaCuentas;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelFoto;
    // End of variables declaration//GEN-END:variables
    Banco cajero = new Banco();
}
